### ISSUE TITLE
Project lacks logo

### ISSUE THREAD

**Issue by andre-filho** [matheusbsilva/pingout#1]
this project needs a logo

assign this to me plz :D

**Comment by matheusbsilva** [comment]
It's assigned :v: ty

**Comment by andre-filho** [comment]
What do you think about these sketches?

![captura de tela de 2018-06-13 10-57-24](https://user-images.githubusercontent.com/15203968/41422018-6b8c4496-6fce-11e8-9bfa-2ebe8e42b5f9.png)
![captura de tela de 2018-06-13 10-57-55](https://user-images.githubusercontent.com/15203968/41422021-6bca8d96-6fce-11e8-88dc-5bfcbc86e29d.png)
![captura de tela de 2018-06-13 10-58-23](https://user-images.githubusercontent.com/15203968/41422022-6bf2801c-6fce-11e8-8815-ff6ee3b31b16.png)

**Comment by matheusbsilva** [comment]
I liked the first one 😀

**Comment by andre-filho** [comment]
Why are we speaking english btw?

**Comment by andre-filho** [comment]
What message you want to pass when people see your logo? (for the main color)
Or do you have a color defined already?

**Comment by matheusbsilva** [comment]
Idk dude, something quick and free :thinking:

**Comment by andre-filho** [comment]
![pingout-alt](https://user-images.githubusercontent.com/15203968/41631899-9ad12c60-740d-11e8-8371-b35d658f2d6e.png)
![pingout](https://user-images.githubusercontent.com/15203968/41631903-9f23478a-740d-11e8-9daf-a0cbd1a04751.png)

**Comment by matheusbsilva** [comment]
![pingout_transparent](https://user-images.githubusercontent.com/14370340/42978617-5260c1b2-8ba4-11e8-932b-89fe566cd730.png)
